name: venia-concept
type: nodejs:10

dependencies:
  nodejs:
    yarn: "1.15.*"

web:
  commands:
    start: NODE_ENV=production yarn stage:venia

hooks:
  build: |
    yarn install
    yarn build:cloud

build:
  flavor: none

variables:
    env:
        MAGENTO_BACKEND_URL: https://venia-concept-el5v5ta-u3uh6xofiwzu2.demo.magentosite.cloud/
        BRAINTREE_TOKEN: sandbox_q7f8z87n_zkw2ctrkj75ndvkc
        MAGENTO_BUILDPACK_PROVIDE_SECURE_HOST: 1
        MAGENTO_BUILDPACK_SECURE_HOST_ADD_UNIQUE_HASH: 0
        PORT: 80
        UPWARD_JS_BIND_LOCAL: 1
        UPWARD_JS_LOG_URL: 0
        UPWARD_JS_UPWARD_PATH: venia-upward.yml

disk: 1024
